### PR TITLE
Support loading parameters from properties for Type=Class.

### LINKED ISSUE #33: For Type="Class", add reflection based property/ParameterGroup discovery support
It would be very useful for me if I could declare a `Task` using the `Class` syntax and let the parameters be automatically discovered just as if my `Task` was declared in an assembly. I think that if I wrote my `Task` as an assembly, MSBuild would use reflection over the properties of my class to discover which properties are supported. This means that if I am overriding an existing `Task` to intercept/extend it, I would automatically inherit the properties it uses and can augment them with additional properties.

However, for `CodeTaskFactory` and `RoslynCodeTaskFactory`, currently the parameters must be explicitly provided via `<ParameterGroup/>`. This makes sense and is even required for `Type="Fragment"` and `Type="Method"`. However, this is quite limiting for my use case of `Type="Class"`.

My idea for the design of this would be to add a new parameter to the `<Code/>` element to enable this capability. Another option is to simply automatically do parameter discovery when `<ParameterGroup/>` is absent and `Type="Class"`. Two hypothetical examples of these options:

Explicit `AutomaticParameters="True"`:

```xml
<UsingTask
  TaskName="Csc"
  TaskFactory="CodeTaskFactory"
  AssemblyFile="$(RoslynCodeTaskFactory)"
  Condition=" '$(RoslynCodeTaskFactory)' != '' ">
  <Task>
    <Reference Include="$(RoslynTargetsPath)\Microsoft.Build.Tasks.CodeAnalysis.dll" />
    <Code Type="Class" Language="cs" AutomaticParameters="True">
      <![CDATA[
        public class Csc : Microsoft.CodeAnalysis.BuildTasks.Csc
        {
          public override bool Execute()
          {
            // Do something interceptive here…

            return base.Execute();
          }
        }
      ]]>
    </Code>
  </Task>
</UsingTask>
```

Implicit omission of `<ParameterGroup/>`:

```xml
<UsingTask
  TaskName="Csc"
  TaskFactory="CodeTaskFactory"
  AssemblyFile="$(RoslynCodeTaskFactory)"
  Condition=" '$(RoslynCodeTaskFactory)' != '' ">
  <Task>
    <Reference Include="$(RoslynTargetsPath)\Microsoft.Build.Tasks.CodeAnalysis.dll" />
    <Code Type="Class" Language="cs">
      <![CDATA[
        public class Csc : Microsoft.CodeAnalysis.BuildTasks.Csc
        {
          public override bool Execute()
          {
            // Do something interceptive here…

            return base.Execute();
          }
        }
      ]]>
    </Code>
  </Task>
</UsingTask>
```

I’m planning to try to implement this. Please let me know if you have any suggestions and if this functionality would be accepted into RoslynCodeTaskFactory.

### PR DESCRIPTION
**Pull request by binki**
When authoring a Task in an assembly, task parameters are declared
simply by creating public properties. CodeTaskFactory instead requires
the user to manually declare all properties in a <ParameterGroup/>
element. This is tedious when using Type="Class" because the
parameters must be listed both as property declarations and in
<ParameterGroup/>. Also, this requirement increases maintenance when
using inheritence to extend or intercept an existing Task from another
assembly.

This change adds an AutoDetectParameters="True" option to the <Code/>
element for Type="Class". When enabled, simple reflection is used to
calculate the parameters and any parameters provided via
<ParameterGroup/> are ignored.

Fixes #33.

### CODE REVIEW

**Comment by binki** [comment]
@jeffkl Thanks for taking time out of your vacation to respond!

**Comment by jeffkl** [comment]
Okay I'm back.  I'll preface this with an apology that I just happened to be on vacation when you submitted the issue and this pull request.

After thinking about it, I'm of the opinion that when a user specifies `CodeTaskFactoryCodeType.Class`, that they should not have to specify the parameters at all.  I would say we have no `AutoDetectParameters` attribute and instead its just be automatic.  As you've pointed out, at the moment users have to specify the parameters in XML and in code already.  We might as well just use reflection and make it automatic.  If a user specifies the parameters in XML, we could just ignore it or log a message saying they were ignored.  This would have no breaking change because existing `<UsingTask />` definitions already have all parameters defined and when a user is specifying a whole class they have their parameters defined.  I think having to opt-in to this automatic behavior would be hard to discover and instead we could just make it opt-in if they specify a whole class.

What do you think?

**Comment by binki** [comment]
I think making it fully automatic should be fine.

Warning that they’re ignored if specified would be the best behavior because users will wonder why removing a parameter from that list fails to remove the parameter from the created task (using the `<ParameterGroup/>` to prevent public properties from being treated as parameters is the only use case I can imagine and I don’t know how that would even be useful). For people switching to/from the MSBuild .netfx built-in CodeTaskFactory and RoslynCodeTaskFactory, the warning may be annoying but will at least permit them to test this out without making additional changes.

This would need to be documented in a list of behavioral differences between RoslynCodeTaskFactory and .netfx CodeTaskFactory.

I can update my PR but it might take me a day to find the time to do so.

**Comment by jeffkl** [comment]
Okay no hurry.  I'm in the process of porting my code task factory directly into MSBuild: https://github.com/Microsoft/msbuild/pull/3175

I'll port your change into that submissions as well after we've merged this.  Thanks for the contribution!

**Comment by binki** [comment]
I’ve updated  to have a warning an ignore any supplied `<ParameterGroup/>` when Type=Class. I’ve removed the README edits for now, not sure they make sense and probably at least doesn’t need to be part of this particular PR. Let me know if there’s anything else I can do to help get this functionality in :-).

**Pull request merged**
